# Generated by Django 2.2.8 on 2022-07-17 16:31

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaryModelForm',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.FloatField()),
                ('buyer', models.BinaryField(editable=True)),
                ('seller', models.BinaryField(editable=True)),
                ('description', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('deadline', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('closed', 'closed')], default='pending', max_length=50)),
                ('type', models.CharField(choices=[('new', 'new'), ('contribute', 'contribute'), ('delete', 'delete')], max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='timestamp',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='event',
            name='times',
            field=models.IntegerField(default=0),
        ),
    ]
